---
- hosts: server
  become: yes
  pre_tasks:
    # - command: apt-get install python-minimal
    - name: 'install python2'
      raw: apt-get -y install python-simplejson

  roles:
    - sensu-server
  tags:
    - sensu-server

# - hosts: client
#   become: yes
#   roles:
#     - sensu-server
#   tags:
#     - client